# Generated by Django 4.2.3 on 2023-07-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_first_name', models.CharField(max_length=255)),
                ('member_last_name', models.CharField(max_length=255)),
                ('member_phone', models.CharField(max_length=15)),
                ('member_email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Members',
        ),
    ]
